---

version: '3.7'

services:
  backend:
    image: ${REGISTRY}-backend:${GITHUB_SHA}
    command: bash -c "
      pwd &&
      coverage run -m unittest discover &&
      coverage report &&
      coverage xml"
    environment:
      - ENV=test
      - MONGODB_USER=test
      - MONGODB_PASS=test2020
      - MONGODB_HOST=mongodb
      - MONGODB_DATABASE=testvideos
      - MONGODB_PORT=27017
    volumes:
      - ./backend:/code  # to access coverage.xml

  db:
    image: ${REGISTRY}-mongodb:${GITHUB_SHA}
    environment:
      - MONGODB_USER=test
      - MONGODB_PASS=test2020
      - MONGODB_HOST=mongodb
      - MONGODB_DATABASE=testvideos
      - MONGODB_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=admintest
      - MONGO_INITDB_ROOT_PASSWORD=admin!test
      - MONGO_INITDB_DATABASE=testvideos
